### PR TITLE
Modify GetPost() to allow inclusion of pinned posts

### LINKED ISSUE #112: JSON Export: Not exporting pinned posts
### Describe the bug
Currently, when a user exports their data via JSON, posts in a collection which are pinned are not included in the exported JSON file.  This behavior is absent from the txt and csv exports (but IS present for the Prettified export).

### Steps to reproduce (if necessary)
1. Create a post.
2. Click on "pin" from that collection's page (i.e. domain-name/my-cool-blog)
3. Go to domain-name/me/export.
4. Click "JSON" or "Prettified" and download the file.
5. Open the JSON file.  The pinned post will be missing from that collection's `posts` value (the array will be empty if there are no unpinned posts in that collection).

### Expected behavior
All posts should be included in the `posts` array, regardless of its `pinned_position` value.

### Application configuration
 - Multi-user mode 
 - Mysql
 - **Open registration?** Yes
 - **Federation enabled?** Yes

**Version or last commit**: 0.9.1

### PR DESCRIPTION
**Pull request by joyeusenoelle**
This PR modifies the `GetPost()` function in [database.go](https://github.com/writeas/writefreely/blob/95e84a1d0e3e23a3156ab624b2f5e9b51ef9a8ba/database.go#L1068-L1123) to add an additional parameter, `includePinned`. When `includePinned` is `false`, the SQL query to fetch posts will include the clause `AND pinned_position IS NULL`; when `includePinned` is `true`, that clause is left out.

In addition, this PR updates all calls to `GetPost()` to include an argument for the new position. Currently this is `false` everywhere but [export.go](https://github.com/writeas/writefreely/blob/95e84a1d0e3e23a3156ab624b2f5e9b51ef9a8ba/export.go#L114), where the argument is `true` to ensure that all posts (including pinned posts) are exported as JSON.

I'm going with this one rather than `fix-json-export` because it's easier to maintain in the future (since we won't have two copies of a largely-identical function to manage).

This should resolve #112.

---

- [x] I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Comment by thebaer** [comment]
Agreed this is the best way to go, and is consistent with how we do this sort of thing in other places. Code looks good at first glance, and I'll test soon.

File: database.go [hunk 1]
```diff
@@ -1089,7 +1089,11 @@ func (db *datastore) GetPosts(c *Collection, page int, includeFuture, forceRecen
 	if !includeFuture {
 		timeCondition = "AND created <= " + db.now()
 	}
-	rows, err := db.Query("SELECT "+postCols+" FROM posts WHERE collection_id = ? AND pinned_position IS NULL "+timeCondition+" ORDER BY created "+order+limitStr, collID)
+	pinnedCondition := ""
+	if !includePinned {
+		pinnedCondition = "AND pinned_position IS NULL"
```
Comment (robjloranger) [inline database.go]: I think you will need a space on the end, `AND pinned_position IS NULL `. Otherwise it will run into `timeCondition`.

Comment (joyeusenoelle) [reply database.go]: The space is included in the query string on line 1096. :)

Comment (robjloranger) [reply database.go]: oh I totally missed that. :blush: 

not that I look though, does white space matter here? I mean extra. for example, if you have only `timeCondition` would the query having two spaces cause an error?

Comment (joyeusenoelle) [reply database.go]: It doesn't. You can see in the deleted row that it's possible to have a double space if `timeCondition` is empty, and SQL doesn't seem to care at all. :)

Comment (robjloranger) [reply database.go]: sweet, thanks for teaching me :)

File: database.go [hunk 2]
```diff
@@ -1065,7 +1065,7 @@ func (db *datastore) GetPostsCount(c *CollectionObj, includeFuture bool) {
 // GetPosts retrieves all standard (non-pinned) posts for the given Collection.
```
Comment (thebaer) [inline database.go]: Just need to update this comment to reflect the option of including pinned posts.

Comment (joyeusenoelle) [reply database.go]: I've updated the docstring as requested. :)

**Comment by thebaer** [comment]
Perfect, thanks!
